#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing & building the project before pushing'

# TODO: Add testing script

# Check Prettier standards
npm run check-format ||
(
    echo '❌ Styling errors — Prettier check failed. ❌
            Run npm run format, add changes and try to push again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '❌ Linting errors — ESLint check failed. ❌
                Make the required changes listed above, add changes and try to push again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌ Typing errors — tsconfig check failed. ❌
            Make the above required changes.'
    false;
)

# If linting, formatting & typing pass, proceed with build
echo '✅ Code is properly typed, linted & formatted ➜ proceeding with build. ✅'

npm run build ||
(
    echo '❌ NextJS build failed. ❌
            View the errors above to see why.'
    false;
)

# Everything passes — time to push
echo '🏆🥳🎉 Successful build ➜ pushing changes. 🎉🥳🏆'
