name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" & "development" branches
  push:
    branches:
      - main
      - development
    paths-ignore:
      - "**/README.md"

  pull_request:
    branches:
      - main
      - development
    paths-ignore:
      - "**/README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains 3 jobs called "run-linters", "Typecheck" & "build"
  run-linters:
    name: Run linters # Name shown on GitHub actions
    timeout-minutes: 2 # Job fails after 2 minutes if not completed
    runs-on: ubuntu-latest # Machine the job is triggered on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci # Cleaner alternative to npm install

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  tsc:
    name: Typecheck
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Run TypeScript check
        run: tsc --noEmit

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Script is running!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
